# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-20 20:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='amount',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
